# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 6.14-1 replay file
# Internal Version: 2014_06_04-20.37.49 134264
# Run by xiaohan on Thu Jun 21 14:19:36 2018
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=442.647888183594, 
    height=208.674087524414)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
openMdb(pathName='/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil.cae')
#: A new model database has been created.
#: The model "Model-1" has been created.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#* MdbError: incompatible release number, expected 6.14-1, got 6.12-4
upgradeMdb(
    "/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil-6.12-4.cae", 
    "/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil.cae", )
#: The model database "/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil_TEMP.cae" has been opened.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
#: The model database has been saved to "/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil.cae".
#: The model database "/home/xiaohan/Desktop/Temp/AbaqusModels/airfoil/airfoil-6.12-4.cae" has been converted.
p1 = mdb.models['Model-1'].parts['airfoil']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['Model-1'].Part(name='airfoil-failed', 
    objectToCopy=mdb.models['Model-1'].parts['airfoil'])
mdb.models['Model-1'].parts['airfoil-failed'].Unlock(reportWarnings=False)
del mdb.models['Model-1'].parts['airfoil']
mdb.models['Model-1'].parts.changeKey(fromName='airfoil-failed', 
    toName='airfoil')
import assembly
mdb.models['Model-1'].rootAssembly.regenerate()
p1 = mdb.models['Model-1'].parts['airfoil']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['Model-1'].parts['airfoil']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
#: Warning: Validity of the geometry was updated after one or more of the selected features.
#: Deleting these features may cause the validity of the geometry to change.
p = mdb.models['Model-1'].parts['airfoil']
p.deleteFeatures(('Partition face-2', 'Partition cell-2', 'Partition cell-1', 
    ))
p = mdb.models['Model-1'].parts['airfoil']
del p.features['Partition face-1']
session.viewports['Viewport: 1'].view.setValues(nearPlane=869.775, 
    farPlane=1456.15, width=424.257, height=229.01, cameraPosition=(32.0663, 
    3.80705, 1412.11), cameraUpVector=(-0.11674, 0.927472, -0.355202), 
    cameraTarget=(75.8208, -17.2113, 271.391))
session.viewports['Viewport: 1'].view.setValues(nearPlane=890.086, 
    farPlane=1414.71, width=434.164, height=234.358, cameraPosition=(465.505, 
    616.123, 1144.43), cameraUpVector=(-0.211344, 0.603206, -0.769075), 
    cameraTarget=(83.7276, -6.04136, 266.508))
session.viewports['Viewport: 1'].view.setValues(nearPlane=936.348, 
    farPlane=1369.72, width=456.73, height=246.539, cameraPosition=(1081.27, 
    283.43, 746.805), cameraUpVector=(-0.449492, 0.817757, -0.359487), 
    cameraTarget=(89.4171, -9.11531, 262.834))
session.viewports['Viewport: 1'].view.setValues(nearPlane=1023.95, 
    farPlane=1262.3, width=499.459, height=269.604, cameraPosition=(403.731, 
    1073.43, 473.126), cameraUpVector=(-0.918147, -0.00141091, -0.396237), 
    cameraTarget=(82.7839, -1.38104, 260.155))
session.viewports['Viewport: 1'].view.setValues(nearPlane=1017.35, 
    farPlane=1269.32, width=496.238, height=267.865, cameraPosition=(177.1, 
    1096.7, 558.445), cameraUpVector=(-0.95031, -0.199934, -0.238616), 
    cameraTarget=(82.5104, -1.35296, 260.258))
session.viewports['Viewport: 1'].view.setValues(nearPlane=933.9, 
    farPlane=1360.8, width=455.533, height=245.893, cameraPosition=(205.336, 
    893.55, 958.776), cameraUpVector=(-0.951959, -0.0605173, -0.300186), 
    cameraTarget=(82.5496, -1.63538, 260.815))
session.viewports['Viewport: 1'].view.setValues(nearPlane=856.136, 
    farPlane=1451.97, width=417.602, height=225.418, cameraPosition=(-42.7022, 
    72.2248, 1395.26), cameraUpVector=(-0.838047, 0.309659, -0.449209), 
    cameraTarget=(81.338, -5.64732, 262.947))
session.viewports['Viewport: 1'].view.setValues(nearPlane=954.645, 
    farPlane=1344.57, width=465.653, height=251.355, cameraPosition=(293.236, 
    942.233, 873.185), cameraUpVector=(-0.918855, 0.054835, -0.390767), 
    cameraTarget=(84.9212, 3.63249, 257.378))
session.viewports['Viewport: 1'].view.setValues(nearPlane=1014.9, 
    farPlane=1280.02, width=495.043, height=267.22, cameraPosition=(-40.6479, 
    1089.41, 589.599), cameraUpVector=(-0.866634, -0.335598, -0.369214), 
    cameraTarget=(82.6374, 4.63918, 255.438))
p = mdb.models['Model-1'].parts['airfoil']
s = p.features['Solid extrude-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s)
s1 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Solid extrude-1'], filter=COPLANAR_EDGES)
s1.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
session.viewports['Viewport: 1'].view.setValues(nearPlane=998.506, 
    farPlane=1296.42, width=688.082, height=371.42, viewOffsetX=40.1477, 
    viewOffsetY=2.68153)
p = mdb.models['Model-1'].parts['airfoil']
s = p.features['Solid extrude-1'].sketch
mdb.models['Model-1'].ConstrainedSketch(name='__edit__', objectToCopy=s)
s2 = mdb.models['Model-1'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Solid extrude-1'], filter=COPLANAR_EDGES)
s2.unsetPrimaryObject()
del mdb.models['Model-1'].sketches['__edit__']
